services:
  jupyter:
    build: .
    ports:
      - "${JUPYTER_PORT}:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./dataset:/home/jovyan/work/dataset:delegated
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: start-notebook.py --NotebookApp.token='${JUPYTER_TOKEN}'
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
