services:
  es:
    build:
      context: .
    ports:
      - "9200:9200" # 엘라스틱 서치 HTTP 포트
      - "9300:9300" # 엘라스틱 서치 TCP 전송 포트
    environment:
      - discovery.type=single-node # 개발 환경을 위한 단일 노드 설정
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # JVM 힙 크기 설정 (필요에 따라 조정)
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601" # Kibana 포트
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    depends_on:
      - es
    networks:
      - es-network

networks:
  es-network:
    driver: bridge